apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elect-leader
  labels:
    app: elect-leader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elect-leader
subjects:
  - name: elect-leader
    namespace: elect-leader
    kind: ServiceAccount