apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elect-leader
  namespace: elect-leader
  labels:
    app: elect-leader
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["*"]